<?php

/**
 * COMMON TITLE
 */
const TITLE_GET_PRODUCT_BY_TYPES = "DANH SÁCH SẢN PHẨM THEO THỂ LOẠI ";
const TITLE_LIST_PRODUCT_DELETE = "DANH SÁCH SẢN PHẨM ĐÃ BỊ XÓA ";
const TITLE_ADD_PRODUCT = "THÊM SẢN PHẨM LỒNG ĐÈN";
const TITLE_EDIT_PRODUCT = "SỬA SẢN PHẨM ĐÈN LỒNG";

const TITLE_LIST_CUSTOMERS = "DANH SÁCH KHÁCH HÀNG";
const TITLE_ADD_CUSTOMER = "THÊM MỚI KHÁCH HÀNG ";
const TITLE_EDIT_CUSTOMER = "CHỈNH SỬA KHÁCH HÀNG";




/**
 * COMMON MESSGAGES
 */
const MESSAGE_DELETE_SUCCESS = "ĐÃ XÓA THÀNH CÔNG!";
const MESSAGE_DELETE_FAIL = "XÓA THẤT BẠI";
const ROLLBACK_STATUS_PRODUCT_SUCCESS = "ĐÃ KHÔI PHỤC TRẠNG THÁI SẢN PHẨM THÀNH CÔNG ";
const ROLLBACK_STATUS_PRODUCT_FAIL = "KHÔI PHỤC SẢN PHẨM THẤT BẠI";
const MESSAGE_ADD_PRODUCT_SUCCESS = "Thêm thành công Sản phẩm";
const MESSAGE_EDIT_PRODUCT_SUCCESS = "Sửa thành công Sản phẩm";
const MESSAGE_ROLLBACK_CUSTOMSER_SUCCESS = "KHÔI PHỤC XÓA KHÁCH HÀNG THÀNH CÔNG";
const MESSAGE_ROLLBACK_CUSTOMER_FAIL = "KHÔI PHỤC XÓA KHÁCH HÀNG THẤT BẠI";
const MESSAGE_EXIST_EMAIL = "Email của bạn bị trùng - Vui lòng kiểm tra lại";
const MESSAGE_ADD_CUSTOMER_SUCCESS = "THÊM KHÁCH HÀNG THÀNH CÔNG ";
const MESSAGE_ADD_CUSTOMER_FAIL= "THÊM KHÁCH HÀNG THẤT BẠI!";
const MESSAGE_UPDATE_CUSTOMER_SUCCESS = "CẬP NHẬT KHÁCH HÀNG THÀNH CÔNG ";
const MESSAGE_UPDATE_CUSTOMER_FAIL = "CẬP NHẬT KHÁCH HÀNG THẤT BẠI";

/**
 * COMMON CONSTANT VARIABLES
 */
// Set status with insert or edit
const DELETE_FLAG_OFF = 0;
const DELETE_FLAG_ON = 1;

/**
 * DIRECTORY FOLDER ADMIN
 */
const DIRECTORY_ADMIN_VIEW = "include/admin.view.php";


